### ISSUE TITLE
How do not cache when ssr get data Error

### ISSUE THREAD

**Issue by lamb-mei** [Kikobeats/cacheable-response#41] opened 2020-02-18 07:46 UTC
Cacheable-response works fine in normal case
But in some cases i don't want to use cache
E.g 
SSR get Data Error, it will cache error page
how to pass this case

**Comment by Kikobeats** [comment] 2020-02-18 09:13
Hello, I think this is a duplicate of #40 

Can you comment in that issue instead? 🙂

**Closed by Kikobeats** 2020-02-18 09:13 UTC
